WIP: copyright/licence in the book deployment
OceanGlidersCommunity/Oxygen_SOP pull request #187
Opened 2021-12-20 11:30 UTC by soerenthomsen

This pull-request will update. 

- [X] author added to _config.yml file: OceanGliders Community
- [X] year added to _config.yml file: "2021" 
- [ ] credit jupyter books
- [ ] mention CC licence and link to repo licence file

2021-12-20 12:38 UTC, soerenthomsen commented
@isgiddy if you have capacity to support this would be amazing.

2022-01-24 08:49 UTC, soerenthomsen commented
@isgiddy and @jbusecke we try to close as many PR and issues of the oxygen SOP this week to close the community review. Do you have capacity to support this PR?

2022-01-24 09:37 UTC, soerenthomsen commented
when adding:     html_show_copyright: false 
to the _config.yml it looks like this

<img width="329" alt="Screen Shot 2022-01-24 at 10 36 54" src="https://user-images.githubusercontent.com/32633545/150757995-e614c51a-16f1-44ff-95b5-985c17dec930.png">
.

2022-01-24 11:07 UTC, isgiddy requested changes
comment out the line author and add the following beneath logo (hope you can see the raw text here):
`html:
extra_footer: 
<p> By the OceanGliders community using <a href="https://jupyterbook.org/intro.html"   target="_blank">Jupyter Book</a>. This work is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank"> Creative Commons Attribution 4.0 Generic License.</a> </p> 
`

2022-01-24 11:34 UTC, soerenthomsen commented
Now it shows like this in the text deployment again: 
<img width="291" alt="Screen Shot 2022-01-24 at 12 31 10" src="https://user-images.githubusercontent.com/32633545/150775753-92209a70-bebd-4262-88f4-e8fa3a2d53e4.png">

2022-01-24 11:53 UTC, soerenthomsen commented
Now the extra_footer works we just need to find a way to fully blend out the author line.
<img width="684" alt="Screen Shot 2022-01-24 at 12 50 51" src="https://user-images.githubusercontent.com/32633545/150778314-69f7f57b-b178-41ac-a57e-fa950f8e4492.png">

2022-01-24 11:58 UTC, soerenthomsen commented
Now it works! Yay!

2022-01-24 11:59 UTC, isgiddy approved these changes
Great!

2022-01-24 12:00 UTC, merged